### ISSUE TITLE
CUDA out of memory issue when using PyTorch weights instead of JAX weights.

### ISSUE THREAD

**Issue by 4BD0U** [google-deepmind/tapnet#94]
Hello,

I have a CUDA out of memory issue when using the PyTorch weights of the Tapir model, particularly when I process a video with 44 frames and 300 points. However, with the Tapir model in JAX, even with 2000 points, I don't encounter any CUDA memory issues. I am using an RTX 3090 GPU with 24GB of VRAM.

Thank you in advance for your help.

**Comment by 4BD0U** [comment]
I solved the problem; I just forgot to add a torch.no_grad() for model inference.

**Comment by yangyi02** [comment]
That is great. Thank you for figuring out!
